Portfolio_Django/portfolio_app/urls.py
from django.urls import URLPattern, path
from . import views


app_name = 'portfolio_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('submitted/', views.submitted, name='submitted')
]

Portfolio_Django/portfolio_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_app.urls')) # Index
]

handler404 = "portfolio_app.views.handle_not_found"

Portfolio_Django/portfolio_app/models.py
from django.db import models

# Create your models here.

class ContactMe(models.Model):
    email = models.EmailField()
    message = models.TextField(max_length=500)
    sent_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Email: {self.email} / Message: {self.message} / sent: {self.sent_time}"

Portfolio_Django/portfolio_app/forms.py
from email import message
from django.forms import ModelForm, Textarea, EmailField
from .models import ContactMe
from django import forms
from captcha.fields import ReCaptchaField
class ContactForm(ModelForm):
    human = ReCaptchaField(label = 'My sites are for humans')
    
    class Meta:
        model = ContactMe
        fields = '__all__'
        
        labels = {
            'message': "Project details",
        }

Portfolio_Django/portfolio_app/views.py
from email import message
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import ContactMe
from django.urls import reverse
from django import forms
from .forms import ContactForm
# from django.core.mail import send_mail
# Create your views here.

def index(request):
    form = ContactForm()
    
    return render(request, 'portfolio_app/index.html', {'form': form})

def handle_not_found(request, exception):
    return render(request, 'portfolio_app/404.html')


def submitted(request):
        if request.POST['g-recaptcha-response'] == '':
            return render(request, 'portfolio_app/500.html')
        elif request.method == 'POST':
            # user_mail = request.POST['email']
            # user_msg = request.POST['message']
            form = ContactForm(request.POST)
            if 'bot' in str(form).lower() or 'robot' in str(form).lower() or 'bucks' in str(form).lower():
                return render(request, 'portfolio_app/contacterror.html')
            elif form.is_valid():
                form.save()
            
        #     send_mail(
        #         'Portfolio Contact',
        #         f"From {user_mail}: {user_msg}",
        #         user_mail,
        #         ['My_email'], 
        #         fail_silently=False,
        #     )
                return render(request, 'portfolio_app/contact_sub.html')

Portfolio_Django/portfolio_app/templates/portfolio_app/contact_sub.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Info Sent!</title>
    <link rel="stylesheet" href="{% static 'portfolio_app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio_app/css/bootstrap.css' %}">
    <link rel="icon" href="{% static 'portfolio_app/images/favicon.svg' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body class="body">
    <nav class="navbar navbar-expand-lg bg-transparent sticky-top">
        <!-- NAV -->
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img id="brand" src="{% static 'portfolio_app/images/GICON.svg' %}"></a>
            <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><img src="{% static 'portfolio_app/images/NAVICON.svg' %}"></span>
          </button>

            <div style="overflow-y: hidden; height: 100px;" class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item fs-1 ">
                        <a class="nav-link text-white" href="/"><span class="comments">&#60;&#33;-</span>Home<span class="comments">-&#62;<span class="comments"></span></a>
                    </li>

                </ul>

            </div>
        </div>
        </div>
    </nav>
    </div>
    </div>

    </nav>
    <span id="sent_cont">
    <h1 id="bio" class="color-white">Your contact information has been sent! I'll be in contact with you soon. Thanks for reaching out. </h1>
    <div class="row">
    <a href="/"><button class="rounded-3 col-8 mx-auto mt-4 p-2 bg-dark text-white" href="/">Home</button></a>
    </div>
  </span>
</body>

</html>

Portfolio_Django/portfolio_app/templates/portfolio_app/contacterror.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact-error</title>
    <link rel="stylesheet" href="{% static 'portfolio_app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio_app/css/bootstrap.css' %}">
    <link rel="icon" href="{% static 'portfolio_app/images/favicon.svg' %}">
    <meta name="author" content="Gage Lieble">

</head>

<body class="error_body" style="background-image: url('/static/portfolio_app/images/TOPO.svg');">
    <h1 style="text-align: center; max-width: 750px;">I've had a lot of bots using my contact form :( so please resend your project details without the phrases "bot" "robot" "bucks". Thank you!</h1>
    <a href="{% url 'portfolio_app:index'%}"><button class="rounded-3 col-8 mx-auto mt-4 p-2 bg-dark text-white w-100" href="/">Home</button></a>
</body>

</html>